Team8-Project/back

src/main/java/com/teamproj/backend/config/MvcConfig.java
src/main/java/com/teamproj/backend/controller/UserController.java
src/main/java/com/teamproj/backend/dto/kakao/KakaoUserInfoDto.java
src/main/java/com/teamproj/backend/dto/kakao/KakaoUserResponseDto.java
src/main/java/com/teamproj/backend/model/User.java
src/main/java/com/teamproj/backend/security/jwt/JwtTokenUtils.java
src/main/java/com/teamproj/backend/service/KakaoUserService.java
src/main/resources/static/index.html

카카오 로그인 기능

---

src/main/java/com/teamproj/backend/controller/UserController.java
src/main/resources/static/index.html

회원가입 기능 Controller에 추가

---

src/main/java/com/teamproj/backend/controller/UserController.java
src/main/java/com/teamproj/backend/dto/user/userInfo/UserInfoResponseDto.java
src/main/java/com/teamproj/backend/service/BoardService.java
src/main/java/com/teamproj/backend/service/UserService.java

BoardService 다듬기

---

src/main/java/com/teamproj/backend/Repository/dict/DictHistoryRepository.java
src/main/java/com/teamproj/backend/Repository/dict/DictRepository.java
src/main/java/com/teamproj/backend/controller/DictController.java
src/main/java/com/teamproj/backend/dto/dict/DictDetailResponseDto.java
src/main/java/com/teamproj/backend/dto/dict/DictPostRequestDto.java
src/main/java/com/teamproj/backend/dto/dict/DictPostResponseDto.java
src/main/java/com/teamproj/backend/dto/dict/DictPutRequestDto.java
src/main/java/com/teamproj/backend/dto/dict/DictPutResponseDto.java
src/main/java/com/teamproj/backend/dto/dict/DictResponseDto.java
src/main/java/com/teamproj/backend/dto/dictHistory/DictHistoryResponseDto.java
src/main/java/com/teamproj/backend/model/dict/Dict.java
src/main/java/com/teamproj/backend/model/dict/DictHistory.java
src/main/java/com/teamproj/backend/model/dict/DictImage.java
src/main/java/com/teamproj/backend/service/DictHistoryService.java
src/main/java/com/teamproj/backend/service/DictService.java
src/main/java/com/teamproj/backend/service/UserService.java

사전 페이지 다듬는중

---

src/main/java/com/teamproj/backend/Repository/CommentRepository.java
src/main/java/com/teamproj/backend/Repository/dict/DictLikeRepository.java
src/main/java/com/teamproj/backend/controller/CommentController.java
src/main/java/com/teamproj/backend/controller/DictController.java
src/main/java/com/teamproj/backend/controller/UserController.java
src/main/java/com/teamproj/backend/dto/comment/CommentDeleteResponseDto.java
src/main/java/com/teamproj/backend/dto/comment/CommentPostRequestDto.java
src/main/java/com/teamproj/backend/dto/comment/CommentPostResponseDto.java
src/main/java/com/teamproj/backend/dto/comment/CommentPutRequestDto.java
src/main/java/com/teamproj/backend/dto/comment/CommentPutResponseDto.java
src/main/java/com/teamproj/backend/dto/dict/DictLikeResponseDto.java
src/main/java/com/teamproj/backend/dto/user/signUp/SignUpCheckResponseDto.java
src/main/java/com/teamproj/backend/model/Comment.java
src/main/java/com/teamproj/backend/model/User.java
src/main/java/com/teamproj/backend/model/dict/Dict.java
src/main/java/com/teamproj/backend/model/dict/DictLike.java
src/main/java/com/teamproj/backend/security/WebSecurityConfig.java
src/main/java/com/teamproj/backend/service/CommentService.java
src/main/java/com/teamproj/backend/service/DictService.java
src/main/java/com/teamproj/backend/service/UserService.java
src/main/java/com/teamproj/backend/util/ManuallyJwtLoginProcessor.java

1. 닉네임 중복확인 기능
2. 아이디 중복확인 기능
3. 사전 작성 기능
4. 사전 조회 기능
5. 사전 좋아요 기능
6. 사전 수정 기능
이하는 테스트 필요 기능
7. 댓글 추가 기능
8. 댓글 삭제 기능
9. 댓글 수정 기능
10. 게시글 별 댓글 목록 조회 기능
11. 게시글 조회 기능
12. 사전 수정 기능

12. 22 오전 작업내역

---

src/main/java/com/teamproj/backend/security/WebSecurityConfig.java

사전 관련 WebSecurity정책 변경

---

src/main/java/com/teamproj/backend/service/KakaoUserService.java

주석 Indent 정리

---

src/main/java/com/teamproj/backend/config/SwaggerConfig.java
src/main/java/com/teamproj/backend/controller/BoardController.java
src/main/java/com/teamproj/backend/controller/DictController.java
src/main/java/com/teamproj/backend/controller/UserController.java
src/main/java/com/teamproj/backend/dto/dictHistory/DictHistoryDetailResponseDto.java
src/main/java/com/teamproj/backend/dto/dictHistory/DictHistoryRecentResponseDto.java
src/main/java/com/teamproj/backend/dto/user/signUp/SignUpRequestDto.java
src/main/java/com/teamproj/backend/exception/ExceptionMessage.java
src/main/java/com/teamproj/backend/model/dict/DictHistory.java
src/main/java/com/teamproj/backend/security/WebSecurityConfig.java
src/main/java/com/teamproj/backend/security/filter/FormLoginFilter.java
src/main/java/com/teamproj/backend/service/CommentService.java
src/main/java/com/teamproj/backend/service/DictHistoryService.java
src/main/java/com/teamproj/backend/service/DictService.java
src/main/java/com/teamproj/backend/service/QuizService.java
src/main/java/com/teamproj/backend/service/UserService.java
src/main/java/com/teamproj/backend/util/ValidChecker.java

사전 롤백 기능 구현 및 코드 리팩토링 작업

---

build.gradle
src/main/java/com/teamproj/backend/BackendApplication.java
src/main/java/com/teamproj/backend/Repository/CarouselImageRepository.java
src/main/java/com/teamproj/backend/Repository/CommentRepository.java
src/main/java/com/teamproj/backend/Repository/dict/DictRepository.java
src/main/java/com/teamproj/backend/config/RedisConfiguration.java
src/main/java/com/teamproj/backend/controller/DictController.java
src/main/java/com/teamproj/backend/controller/MainController.java
src/main/java/com/teamproj/backend/dto/main/MainPageResponseDto.java
src/main/java/com/teamproj/backend/dto/main/MainTodayMemeResponseDto.java
src/main/java/com/teamproj/backend/security/WebSecurityConfig.java
src/main/java/com/teamproj/backend/service/CommentService.java
src/main/java/com/teamproj/backend/service/DictService.java
src/main/java/com/teamproj/backend/service/MainService.java

1. Redis 설정
2. Comment 버그 수정
3. 사전 검색 기능 구현
4. 메인페이지 구현
5. 사전 추천검색어 받기 URL 수정

Redis 설정 외

---

src/main/java/com/teamproj/backend/Repository/stat/StatBoardModifyRepository.java
src/main/java/com/teamproj/backend/Repository/stat/StatQuizSolverRepository.java
src/main/java/com/teamproj/backend/Repository/stat/StatQuizStarterRepository.java
src/main/java/com/teamproj/backend/Repository/stat/StatVisitorRepository.java
src/main/java/com/teamproj/backend/controller/QuizController.java
src/main/java/com/teamproj/backend/controller/StatController.java
src/main/java/com/teamproj/backend/controller/UserController.java
src/main/java/com/teamproj/backend/dto/board/BoardResponseDto.java
src/main/java/com/teamproj/backend/dto/board/BoardSearchResponseDto.java
src/main/java/com/teamproj/backend/dto/dict/DictDetailResponseDto.java
src/main/java/com/teamproj/backend/dto/dict/DictPostRequestDto.java
src/main/java/com/teamproj/backend/dto/dict/DictPutRequestDto.java
src/main/java/com/teamproj/backend/dto/dict/DictResponseDto.java
src/main/java/com/teamproj/backend/dto/dict/DictSearchResultResponseDto.java
src/main/java/com/teamproj/backend/dto/dictHistory/DictHistoryDetailResponseDto.java
src/main/java/com/teamproj/backend/model/dict/Dict.java
src/main/java/com/teamproj/backend/model/dict/DictHistory.java
src/main/java/com/teamproj/backend/model/statistics/StatBoardModify.java
src/main/java/com/teamproj/backend/model/statistics/StatQuizSolver.java
src/main/java/com/teamproj/backend/model/statistics/StatQuizStarter.java
src/main/java/com/teamproj/backend/model/statistics/StatVisitor.java
src/main/java/com/teamproj/backend/security/WebSecurityConfig.java
src/main/java/com/teamproj/backend/service/DictHistoryService.java
src/main/java/com/teamproj/backend/service/DictService.java
src/main/java/com/teamproj/backend/service/QuizService.java
src/main/java/com/teamproj/backend/service/StatService.java
src/main/java/com/teamproj/backend/util/StatisticsUtils.java

[Stastics] 통계 작업

---

build.gradle
src/main/java/com/teamproj/backend/controller/BoardController.java
src/main/java/com/teamproj/backend/model/board/Board.java
src/main/java/com/teamproj/backend/service/BoardService.java
src/main/java/com/teamproj/backend/service/RedisService.java
src/main/java/com/teamproj/backend/util/RedisKey.java
src/main/java/com/teamproj/backend/util/Scheduler.java
src/test/java/com/teamproj/backend/service/BoardServiceTest.java

Feat/board 해시태그 추천 기능 수정

---

src/main/java/com/teamproj/backend/Repository/board/BoardHashTagRepository.java
src/main/java/com/teamproj/backend/service/BoardService.java

Fix/board 업데이트 해시태그

---

src/main/java/com/teamproj/backend/Repository/board/BoardRepository.java
src/main/java/com/teamproj/backend/Repository/board/BoardTodayLikeRepository.java
src/main/java/com/teamproj/backend/controller/MainController.java
src/main/java/com/teamproj/backend/dto/main/MainPageResponseDto.java
src/main/java/com/teamproj/backend/model/board/BoardTodayLike.java
src/main/java/com/teamproj/backend/service/BoardService.java
src/main/java/com/teamproj/backend/service/MainService.java
src/main/java/com/teamproj/backend/service/RedisService.java
src/main/java/com/teamproj/backend/util/Scheduler.java

[Main] 메인페이지 인기게시글, 명예의전당 완료

---

src/main/java/com/teamproj/backend/dto/MyPage/MyPageDictResponseDto.java
src/main/java/com/teamproj/backend/dto/MyPage/MyPagePostBoard.java
src/main/java/com/teamproj/backend/dto/MyPage/MyPageResponseDto.java
src/main/java/com/teamproj/backend/service/MyPageService.java

dict , postBoards  response 추가

Fix/MyPage reponse 수정

---

src/main/java/com/teamproj/backend/Repository/board/BoardHashTagRepository.java
src/main/java/com/teamproj/backend/service/BoardHashTagService.java
src/main/java/com/teamproj/backend/service/BoardService.java

중복되는 코드 정리
- BoardService에서 중복되는 코드는 메서드로 빼서 관리

Fix/boardSearvice 리팩토링

---

.travis.yml

travis-deploy 브랜치에 push 하면 자동배포됩니다.

[CI] Travis-CI 적용

---

.travis.yml
src/main/java/com/teamproj/backend/dto/dictHistory/DictHistoryRecentResponseDto.java
src/main/java/com/teamproj/backend/service/DictHistoryService.java
src/main/java/com/teamproj/backend/service/DictService.java
src/main/java/com/teamproj/backend/service/UserService.java

- 사전 수정 내역에 사용자 프로필 사진도 나오도록.
- 사전 수정 시 최근 변경한 사람 바뀌지 않는 문제.
- 닉네임 최대 길이 10자까지로 수정.

요구사항 수정에 따른 변경

---

src/main/java/com/teamproj/backend/util/JwtAuthenticateProcessor.java

travis 배포 테스트를 위한 작은 수정..

---

src/test/java/com/teamproj/backend/service/BoardServiceTest.java

ArrayList final로 설정해줘서 Builder에서 빠졌습니다

[Test] Board 수정에 따른 Test 소폭 수정

---

src/main/java/com/teamproj/backend/dto/dictHistory/DictHistoryDetailResponseDto.java
src/main/java/com/teamproj/backend/dto/dictHistory/DictHistoryResponseDto.java
src/main/java/com/teamproj/backend/service/DictHistoryService.java

사전 수정내역 및 수정내역 상세에서,
최초 작성자의 프로필사진과 사전의 최초 생성일자를 불러오도록 변경했습니다.

[Dict] 요구사항 수정에 따른 변경

---

src/main/java/com/teamproj/backend/dto/dictHistory/DictHistoryDetailResponseDto.java
src/main/java/com/teamproj/backend/service/DictHistoryService.java

[Dict] 사전 수정 내역 DTO 수정

---

src/main/java/com/teamproj/backend/service/CommentService.java

[Comment] profileImage 주소 누락되어있는 문제 해결

---

appspec.yml

[CI/CD] 배포자동화 진짜 최종

---

appspec.yml
execute-deploy.sh
src/main/java/com/teamproj/backend/controller/DictController.java
src/main/java/com/teamproj/backend/dto/dict/DictNameCheckRequestDto.java
src/main/java/com/teamproj/backend/service/DictService.java

[Dict] 사전 이름 검색 기능 수정

---

appspec.yml
execute-deploy.sh
src/main/java/com/teamproj/backend/controller/DictController.java
src/main/java/com/teamproj/backend/dto/dict/DictNameCheckRequestDto.java
src/main/java/com/teamproj/backend/service/BoardHashTagService.java
src/main/java/com/teamproj/backend/service/DictService.java
src/main/resources/real-application.yml

feat/dict and Bug fix boardHashTagRecommend

---

src/main/java/com/teamproj/backend/BackendApplication.java

Reverts Team8-Project/back#201

Revert "[CI/CD] nginx test"

---

src/main/java/com/teamproj/backend/OAuth2/CustomOAuth2UserService.java
src/main/java/com/teamproj/backend/OAuth2/OAuth2UserProviderFactory.java
src/main/java/com/teamproj/backend/OAuth2/Social.java
src/main/java/com/teamproj/backend/OAuth2/handler/CustomAuthenticationSuccessHandler.java
src/main/java/com/teamproj/backend/controller/MyPageController.java
src/main/java/com/teamproj/backend/dto/mypage/MyPageDictResponseDto.java
src/main/java/com/teamproj/backend/dto/mypage/MyPagePostBoardResponseDto.java
src/main/java/com/teamproj/backend/dto/mypage/MyPageProfileImageModifyResponseDto.java
src/main/java/com/teamproj/backend/dto/mypage/MyPageResponseDto.java
src/main/java/com/teamproj/backend/service/BoardHashTagService.java
src/main/java/com/teamproj/backend/service/BoardService.java
src/main/java/com/teamproj/backend/service/MyPageService.java

- BoardService
- MyPage
- BoardHashTag

feat/board 주석

---

src/main/java/com/teamproj/backend/Repository/CarouselImageRepository.java
src/main/java/com/teamproj/backend/util/Scheduler.java

[Carousel] 에러 수정

---

src/main/java/com/teamproj/backend/model/board/Board.java
src/main/java/com/teamproj/backend/service/BoardService.java
src/main/java/com/teamproj/backend/service/MainService.java

[Main] 핫밈글 받아오기 로직 수정

---

src/main/java/com/teamproj/backend/controller/StatController.java
src/main/java/com/teamproj/backend/model/board/BoardViewers.java
src/main/java/com/teamproj/backend/security/WebSecurityConfig.java
src/main/java/com/teamproj/backend/service/BoardService.java
src/main/java/com/teamproj/backend/service/StatService.java

[Stat] 게시글 수정시 통계에 반영
[Stat] 방문자 기록, 문제 푼 사람 기능

[Stat] 게시글 수정시 통계에 반영 외

---

src/main/java/com/teamproj/backend/dto/dict/DictSearchResultResponseDto.java
src/main/java/com/teamproj/backend/service/DictService.java
src/test/java/com/teamproj/backend/service/DictServiceTest.java

List 여러 번 호출하는 방식 -> Map 한 번 호출하는 방식
빨라졌어요. 10배 정도

[Dict] 좋아요, 좋아요 취소 기능 성능 개선

---

src/main/java/com/teamproj/backend/Repository/board/BoardRepository.java
src/main/java/com/teamproj/backend/Repository/dict/DictRepository.java
src/main/java/com/teamproj/backend/exception/RestApiExceptionHandler.java
src/main/java/com/teamproj/backend/service/BoardService.java
src/main/java/com/teamproj/backend/service/CommentService.java
src/main/java/com/teamproj/backend/service/DictService.java
src/main/java/com/teamproj/backend/util/MemegleServiceStaticMethods.java
src/test/java/com/teamproj/backend/service/DictServiceTest.java

[Board] 조회 성능 개선

---

src/main/java/com/teamproj/backend/Repository/board/BoardHashTagRepository.java
src/main/java/com/teamproj/backend/controller/BoardController.java
src/main/java/com/teamproj/backend/controller/BoardHashTagController.java
src/main/java/com/teamproj/backend/dto/BoardHashTag/BoardHashTagResponseDto.java
src/main/java/com/teamproj/backend/dto/BoardHashTag/BoardHashTagSearchResponseDto.java
src/main/java/com/teamproj/backend/exception/ExceptionMessages.java
src/main/java/com/teamproj/backend/model/board/BoardHashTag.java
src/main/java/com/teamproj/backend/security/WebSecurityConfig.java
src/main/java/com/teamproj/backend/service/BoardHashTagService.java
src/main/java/com/teamproj/backend/util/S3Uploader.java
src/test/java/com/teamproj/backend/service/BoardServiceTest.java

feat/해시태그 검색기능

---

src/main/java/com/teamproj/backend/Repository/dict/DictCuriousRepository.java
src/main/java/com/teamproj/backend/controller/DictCuriousController.java
src/main/java/com/teamproj/backend/controller/RankController.java
src/main/java/com/teamproj/backend/dto/dict/DictNameCheckResponseDtoNeo.java
src/main/java/com/teamproj/backend/dto/dictCurious/DictCuriousPostRequestDto.java
src/main/java/com/teamproj/backend/dto/dictCurious/DictCuriousPostResponseDto.java
src/main/java/com/teamproj/backend/dto/dictCurious/DictCuriousResponseDto.java
src/main/java/com/teamproj/backend/dto/rank/RankDictAllTimeResponseDto.java
src/main/java/com/teamproj/backend/dto/rank/RankResponseDto.java
src/main/java/com/teamproj/backend/exception/ExceptionMessages.java
src/main/java/com/teamproj/backend/model/admin/BanList.java
src/main/java/com/teamproj/backend/model/dict/DictCurious.java
src/main/java/com/teamproj/backend/security/WebSecurityConfig.java
src/main/java/com/teamproj/backend/service/AdminService.java
src/main/java/com/teamproj/backend/service/BoardService.java
src/main/java/com/teamproj/backend/service/DictCuriousService.java
src/main/java/com/teamproj/backend/service/DictService.java
src/main/java/com/teamproj/backend/service/RankService.java
src/main/java/com/teamproj/backend/util/Scheduler.java

[newFunc] 추가 기능 껍데기 추가

---

src/main/java/com/teamproj/backend/Repository/dict/QuestionCommentLikeRepository.java
src/main/java/com/teamproj/backend/Repository/dict/QuestionSelectRepository.java
src/main/java/com/teamproj/backend/controller/DictQuestionCommentController.java
src/main/java/com/teamproj/backend/dto/dict/question/comment/DictQuestionCommentResponseDto.java
src/main/java/com/teamproj/backend/exception/ExceptionMessages.java
src/main/java/com/teamproj/backend/model/dict/question/QuestionCommentLike.java
src/main/java/com/teamproj/backend/service/dict/DictQuestionCommentService.java
src/main/java/com/teamproj/backend/service/dict/DictQuestionService.java
src/main/java/com/teamproj/backend/util/MemegleServiceStaticMethods.java

- 게시판 -> 질문
- 질문 채택 기능
- 게시판 좋아요 -> 질문 나도 궁금해요
- 목록 출력시 댓글의 좋아요 및 개수도 함께 출력
- 댓글 좋아요 기능

[newFunc] 새로 만들어진 기능 반영

---

src/main/java/com/teamproj/backend/Repository/dict/DictRepository.java
src/main/java/com/teamproj/backend/service/dict/DictService.java

[Dict] 사전 검색 containing으로 복구

---

src/main/java/com/teamproj/backend/Repository/dict/DictRepository.java
src/main/java/com/teamproj/backend/controller/DictController.java
src/main/java/com/teamproj/backend/controller/StatController.java
src/main/java/com/teamproj/backend/dto/statistics/StatDictPostByDayDto.java
src/main/java/com/teamproj/backend/dto/statistics/StatDictQuestionListDto.java
src/main/java/com/teamproj/backend/dto/statistics/StatDictResponseDto.java
src/main/java/com/teamproj/backend/security/WebSecurityConfig.java
src/main/java/com/teamproj/backend/service/RankService.java
src/main/java/com/teamproj/backend/service/RedisService.java
src/main/java/com/teamproj/backend/service/StatService.java
src/main/java/com/teamproj/backend/service/dict/DictQuestionService.java
src/main/java/com/teamproj/backend/service/dict/DictService.java
src/main/java/com/teamproj/backend/util/RedisKey.java

1. 통계 기능 추가
2. 질문 조회 기능 성능 개선(쿼리 호출 횟수 감소)

[Dict] 사전 페이지 기능 추가

---

src/main/java/com/teamproj/backend/service/StatService.java

[Dict] Redis 제외 후 배포

---

src/main/java/com/teamproj/backend/config/MvcConfig.java

[Common] CORS 정책 변경

---

src/main/java/com/teamproj/backend/Repository/dict/DictRepository.java
src/main/java/com/teamproj/backend/Repository/dict/DictViewersRepository.java
src/main/java/com/teamproj/backend/Repository/dict/DictYoutubeUrlRepository.java
src/main/java/com/teamproj/backend/controller/DictController.java
src/main/java/com/teamproj/backend/model/dict/question/DictQuestion.java
src/main/java/com/teamproj/backend/service/dict/DictQuestionCommentService.java
src/main/java/com/teamproj/backend/service/dict/DictQuestionService.java
src/main/java/com/teamproj/backend/service/dict/DictService.java
src/main/java/com/teamproj/backend/util/Scheduler.java

쿼리 조회 횟수 감소. 사용자 정보 확인 제외하면 2회 시행됩니다.

[Dict] 사전 및 사전질문 상세보기, 목록보기 성능 개선

---

build.gradle
src/main/java/com/teamproj/backend/controller/BoardController.java
src/main/java/com/teamproj/backend/service/KakaoUserService.java
src/test/java/com/teamproj/backend/service/dict/DictQuestionCommentServiceTest.java

- 센트리 적용
- DictQuestionCommentService 테스트코드 추가
- 카카오 redirect url 변경

Feat/kakao redircet url 변경

---

src/main/java/com/teamproj/backend/model/dict/question/DictQuestion.java
src/main/java/com/teamproj/backend/service/dict/DictQuestionService.java

Fix/DictQuestion 수정 버그

---

src/main/java/com/teamproj/backend/service/GoogleUserService.java
src/main/java/com/teamproj/backend/service/KakaoUserService.java
src/main/java/com/teamproj/backend/service/dict/DictQuestionService.java

- 구글, 카카오 소셜 로그인 redirect url 수정

feat/social login url 변경

---

src/main/java/com/teamproj/backend/Repository/board/BoardViewersRepository.java
src/main/java/com/teamproj/backend/config/MvcConfig.java
src/main/java/com/teamproj/backend/dto/board/BoardDetail/BoardDetailResponseDto.java
src/main/java/com/teamproj/backend/dto/board/BoardResponseDto.java
src/main/java/com/teamproj/backend/model/board/BoardCategory.java
src/main/java/com/teamproj/backend/service/BoardService.java
src/main/java/com/teamproj/backend/service/StatService.java
src/main/java/com/teamproj/backend/service/dict/DictService.java
src/test/java/com/teamproj/backend/service/DictServiceTest.java

[Board] 짤방게시판 성능 개선

---

build.gradle
src/main/java/com/teamproj/backend/controller/DictController.java
src/main/java/com/teamproj/backend/controller/QuizController.java
src/main/java/com/teamproj/backend/model/dict/DictCurious.java
src/main/java/com/teamproj/backend/model/quiz/Quiz.java
src/main/java/com/teamproj/backend/service/NaverUserService.java
src/main/java/com/teamproj/backend/service/QuizService.java
src/main/java/com/teamproj/backend/service/RankService.java
src/main/java/com/teamproj/backend/service/YoutubeService.java
src/main/java/com/teamproj/backend/service/dict/DictService.java
src/test/java/com/teamproj/backend/controller/DictControllerTest.java
src/test/java/com/teamproj/backend/controller/UserControllerTest.java
src/test/java/com/teamproj/backend/service/BoardServiceTest.java
src/test/java/com/teamproj/backend/service/QuizServiceTest.java
src/test/java/com/teamproj/backend/service/YoutubeServiceTest.java
src/test/java/com/teamproj/backend/service/dict/DictServiceTest.java
src/test/java/com/teamproj/backend/service/stat/RankServiceTest.java
src/test/java/com/teamproj/backend/service/user/NaverUserServiceTest.java
src/test/java/com/teamproj/backend/service/user/UserServiceTest.java

[Test] 테스트코드 작성
